---
- add_host:
    groupname=ec2instances
    hostname="{{item.public_ip}}"
    instance_tags="{{item.tags}}"
    ansible_user=centos
    ansible_ssh_host="{{ 'localhost' if local_provision is defined else item.public_ip }}"
    ansible_ssh_port="{{2222 if local_provision is defined else 22}}"
    ansible_ssh_private_key_file="../../treadmill/treadmill/ms_us_west_key_new.pem"
  with_items: "{{created_instances.tagged_instances}}"

- name: Wait for SSH
  local_action:
    wait_for host="{{ 'localhost' if local_provision is defined else item.public_ip }}"
    port="{{2222 if local_provision is defined else 22}}"
    delay=10
    timeout=240
    state=started
  with_items: "{{created_instances.tagged_instances}}"
