---
- name: Create VPC Subnet
  ec2_vpc_subnet:
    vpc_id: "{{ vpc_info.vpc.id }}"
    cidr: "{{ item.value.cidr }}"
    az: "{{ item.value.az }}"
    tags: { "Name":"{{ item.value.name }}", "Type":"{{ item.value.type }}" }
    region: "{{ vpc.region }}"
  with_dict: "{{vpc.subnet}}"