---
- name: Fetch db Server EC2 Facts
  ec2_remote_facts:
    filters:
      instance-state-name: [running, pending]
      "tag:Name": "{{ instance.db_server.name }}"
    region: "{{ vpc.region }}"
  register: instance_facts_db


- debug:
    msg: "{{instance_facts_db.instances[0].public_ip_address}}"